-- MySQL Script generated by MySQL Workbench
-- Thu Aug 22 23:50:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema e_learning_course_service
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `e_learning_course_service` ;

-- -----------------------------------------------------
-- Schema e_learning_course_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e_learning_course_service` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `e_learning_course_service` ;

-- -----------------------------------------------------
-- Table `e_learning_course_service`.`semesters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_learning_course_service`.`semesters` ;

CREATE TABLE IF NOT EXISTS `e_learning_course_service`.`semesters` (
  `id` VARCHAR(255) NOT NULL,
  `semester_code` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `e_learning_course_service`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_learning_course_service`.`courses` ;

CREATE TABLE IF NOT EXISTS `e_learning_course_service`.`courses` (
  `id` VARCHAR(255) NOT NULL,
  `course_code` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `semester_id` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `courses_semester_id_foreign` (`semester_id` ASC) VISIBLE,
  CONSTRAINT `courses_semester_id_foreign`
    FOREIGN KEY (`semester_id`)
    REFERENCES `e_learning_course_service`.`semesters` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `e_learning_course_service`.`course_classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_learning_course_service`.`course_classes` ;

CREATE TABLE IF NOT EXISTS `e_learning_course_service`.`course_classes` (
  `id` VARCHAR(255) NOT NULL,
  `class_code` VARCHAR(255) NOT NULL,
  `course_id` VARCHAR(255) NOT NULL,
  `instructor_id` VARCHAR(255) NOT NULL,
  `assistant_id` VARCHAR(255) NOT NULL,
  `schedule` VARCHAR(255) NOT NULL,
  `capacity` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `course_classes_course_id_foreign` (`course_id` ASC) VISIBLE,
  CONSTRAINT `course_classes_course_id_foreign`
    FOREIGN KEY (`course_id`)
    REFERENCES `e_learning_course_service`.`courses` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `e_learning_course_service`.`students_join_classs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_learning_course_service`.`students_join_classs` ;

CREATE TABLE IF NOT EXISTS `e_learning_course_service`.`students_join_classs` (
  `id` VARCHAR(255) NOT NULL,
  `class_id` VARCHAR(255) NOT NULL,
  `student_code` VARCHAR(255) NOT NULL,
  `created_at` VARCHAR(255) NOT NULL,
  `updated_at` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `students_join_classs_class_id_foreign` (`class_id` ASC) VISIBLE,
  CONSTRAINT `students_join_classs_class_id_foreign`
    FOREIGN KEY (`class_id`)
    REFERENCES `e_learning_course_service`.`course_classes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
