spring.datasource:
  url: jdbc:mysql://localhost:3306/elearning_users
  username: 'root'
  password: '17052002'

spring.jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  defer-datasource-initialization: true

spring.sql:
  init:
    mode: always

spring.cloud:
  kubernetes:
    discovery:
      all-namespaces: true
      discovery-server-url: http://spring-cloud-kubernetes-discoveryserver:80/