-- MySQL Script generated by MySQL Workbench
-- Fri Aug 23 00:12:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema e_learning_material_service
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `e_learning_material_service` ;

-- -----------------------------------------------------
-- Schema e_learning_material_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e_learning_material_service` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `e_learning_material_service` ;

-- -----------------------------------------------------
-- Table `e_learning_material_service`.`class_livestream`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_learning_material_service`.`class_livestream` ;

CREATE TABLE IF NOT EXISTS `e_learning_material_service`.`class_livestream` (
  `id` VARCHAR(255) NOT NULL,
  `time_class_in_date_id` VARCHAR(255) NOT NULL,
  `uploader_id` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `path_url` VARCHAR(255) NOT NULL,
  `material_type` ENUM('DOCUMENT', 'VIDEO', 'IMAGE', 'AUDIO') NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `e_learning_material_service`.`class_materials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_learning_material_service`.`class_materials` ;

CREATE TABLE IF NOT EXISTS `e_learning_material_service`.`class_materials` (
  `id` VARCHAR(255) NOT NULL,
  `time_class_in_date_id` VARCHAR(255) NOT NULL,
  `instructor_id` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `stream_url` VARCHAR(255) NOT NULL,
  `start_time` TIMESTAMP NOT NULL,
  `end_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
