-- MySQL Script generated by MySQL Workbench
-- Fri Aug 23 00:11:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema e_learning_timestable_service
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `e_learning_timestable_service` ;

-- -----------------------------------------------------
-- Schema e_learning_timestable_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e_learning_timestable_service` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `e_learning_timestable_service` ;

-- -----------------------------------------------------
-- Table `e_learning_timestable_service`.`time_classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_learning_timestable_service`.`time_classes` ;

CREATE TABLE IF NOT EXISTS `e_learning_timestable_service`.`time_classes` (
  `id` VARCHAR(255) NOT NULL,
  `course_code` VARCHAR(255) NOT NULL,
  `instructor_id` VARCHAR(255) NOT NULL,
  `class_code` VARCHAR(255) NOT NULL,
  `class_name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `e_learning_timestable_service`.`timetables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_learning_timestable_service`.`timetables` ;

CREATE TABLE IF NOT EXISTS `e_learning_timestable_service`.`timetables` (
  `id` VARCHAR(255) NOT NULL,
  `semester_code` VARCHAR(255) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `e_learning_timestable_service`.`week_shedules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_learning_timestable_service`.`week_shedules` ;

CREATE TABLE IF NOT EXISTS `e_learning_timestable_service`.`week_shedules` (
  `id` VARCHAR(255) NOT NULL,
  `timetables_id` VARCHAR(255) NOT NULL,
  `week_num` INT NOT NULL,
  `start_week` DATE NOT NULL,
  `end_week` DATE NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `week_shedules_timetables_id_foreign` (`timetables_id` ASC) VISIBLE,
  CONSTRAINT `week_shedules_timetables_id_foreign`
    FOREIGN KEY (`timetables_id`)
    REFERENCES `e_learning_timestable_service`.`timetables` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `e_learning_timestable_service`.`date_shedules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_learning_timestable_service`.`date_shedules` ;

CREATE TABLE IF NOT EXISTS `e_learning_timestable_service`.`date_shedules` (
  `id` VARCHAR(255) NOT NULL,
  `week_id` VARCHAR(255) NOT NULL,
  `date` ENUM('MONDAY', 'TUESDAY', 'THURSDAY', 'WEDNESDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY') NOT NULL,
  `is_holiday` ENUM('TRUE', 'FALSE') NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `date_shedules_fk_idx` (`week_id` ASC) VISIBLE,
  CONSTRAINT `date_shedules_fk`
    FOREIGN KEY (`week_id`)
    REFERENCES `e_learning_timestable_service`.`week_shedules` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `e_learning_timestable_service`.`class_in_date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_learning_timestable_service`.`class_in_date` ;

CREATE TABLE IF NOT EXISTS `e_learning_timestable_service`.`class_in_date` (
  `id` VARCHAR(255) NOT NULL,
  `time_class_id` VARCHAR(255) NOT NULL,
  `date_id` VARCHAR(255) NOT NULL,
  `start_time` TIMESTAMP NOT NULL,
  `end_time` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `class_in_date_time_class_id_foreign` (`time_class_id` ASC) VISIBLE,
  INDEX `class_in_date_fk_date_schedule_idx` (`date_id` ASC) VISIBLE,
  CONSTRAINT `class_in_date_time_class_id_foreign`
    FOREIGN KEY (`time_class_id`)
    REFERENCES `e_learning_timestable_service`.`time_classes` (`id`),
  CONSTRAINT `class_in_date_fk_date_schedule`
    FOREIGN KEY (`date_id`)
    REFERENCES `e_learning_timestable_service`.`date_shedules` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
