spring.datasource:
  url: jdbc:mysql://db-mysql-nyc3-60473-do-user-17787633-0.i.db.ondigitalocean.com:25060/elearning_courses
  username: 'doadmin'
  password: 'AVNS_0XadlPN1LVlYrnzEEu4'

spring.jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  defer-datasource-initialization: true

spring.sql:
  init:
    mode: always

spring.cloud:
  kubernetes:
    discovery:
      all-namespaces: true
      discovery-server-url: http://spring-cloud-kubernetes-discoveryserver:80/