-- MySQL Script generated by MySQL Workbench
-- Fri Aug 23 00:05:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema e_learning_grade_service
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `e_learning_grade_service` ;

-- -----------------------------------------------------
-- Schema e_learning_grade_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e_learning_grade_service` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `e_learning_grade_service` ;

-- -----------------------------------------------------
-- Table `e_learning_grade_service`.`weight_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_learning_grade_service`.`weight_grade` ;

CREATE TABLE IF NOT EXISTS `e_learning_grade_service`.`weight_grade` (
  `id` VARCHAR(255) NOT NULL,
  `attendace_weight` DECIMAL(8,2) NOT NULL,
  `assignment_weight` DECIMAL(8,2) NOT NULL,
  `midterm_weight` DECIMAL(8,2) NOT NULL,
  `practical_weight` DECIMAL(8,2) NOT NULL,
  `final_weight` DECIMAL(8,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `e_learning_grade_service`.`grade_class_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_learning_grade_service`.`grade_class_course` ;

CREATE TABLE IF NOT EXISTS `e_learning_grade_service`.`grade_class_course` (
  `id` VARCHAR(255) NOT NULL,
  `class_code` VARCHAR(255) NOT NULL,
  `course_code` VARCHAR(255) NOT NULL,
  `weight_grade_id` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `grade_class_course_fk_idx` (`weight_grade_id` ASC) VISIBLE,
  CONSTRAINT `grade_class_course_fk`
    FOREIGN KEY (`weight_grade_id`)
    REFERENCES `e_learning_grade_service`.`weight_grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `e_learning_grade_service`.`student_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_learning_grade_service`.`student_grade` ;

CREATE TABLE IF NOT EXISTS `e_learning_grade_service`.`student_grade` (
  `id` VARCHAR(255) NOT NULL,
  `class_course_id` VARCHAR(255) NOT NULL,
  `attendace_score` DECIMAL(8,2) NOT NULL,
  `assignment_score` DECIMAL(8,2) NOT NULL,
  `midterm_score` DECIMAL(8,2) NOT NULL,
  `practical_score` DECIMAL(8,2) NOT NULL,
  `final_score` DECIMAL(8,2) NOT NULL,
  `total_score` DECIMAL(8,2) NOT NULL,
  `type_grade` ENUM('A+', 'A', 'B+', 'B', 'C+', 'C', 'D+', 'D', 'F') NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `student_grade_fk_idx` (`class_course_id` ASC) VISIBLE,
  CONSTRAINT `student_grade_fk`
    FOREIGN KEY (`class_course_id`)
    REFERENCES `e_learning_grade_service`.`grade_class_course` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
