server:
  port: 9010

spring:
  application:
    name: enrollments
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: "prod"
  config:
    import: optional:configserver:http://localhost:8071

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: ${spring.application.name}
    description: "E-Learning enrollments application"
    version: "1.0.0"

logging:
  level:
    com:
      didan:
        elearning:
          users: debug
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"